---
dependency:
  name: galaxy
  options:
   requirements-file: requirements.yml
driver:
  name: delegated
platforms:
 - name: 10.51.0.12 
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../hosts
      host_vars: ../../host_vars/
verifier:
  name: ansible
