---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
 - name: None
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../hosts
      host_vars: ../../host_vars/
verifier:
  name: ansible
