slz_name: name
slz_region: region
slz_prefix: prefix
slz_ssh_key: ssh_key
client_config: {
squid: { enable: false, squid_server_ip_port: "10.30.10.4:3128", no_proxy_hosts: "161.0.0.0/8" },
ntp: { enable: true, ntp_server_ip: "127.0.0.1" },
nfs: { enable: false, nfs_server_path: "127.0.0.1:/NFS;127.0.0.1:/hana/software", nfs_client_path: "/mnt;/hana" },
dns: { enable: false, dns_server_ip: "127.0.0.1" }
}
# ----------------------------- Mandatory parameters -----------------------------  #
# Defining all mandatory variables, required to run complete automation suite. Please refer to README if inidividual modules are to be executed and for explianation for variables.

sap_solution: HANA
sap_domain: 'poc.cloud'
# As a dictionary
disks_configuration: {
counts: [2,2,1],
names: [data,log,shared],
paths: [/hana/data,/hana/log,/hana/shared],
wwns: [600507681082018bc8000000000057e4,600507681082018bc8000000000057e8,600507681082018bc8000000000057e5,600507681082018bc8000000000057e6,600507681082018bc8000000000057e7]
}

# As a list. Only one type should be present in variable file. Uncomment if you want to use disks_configuration as a list.
#disks_configuration: [
#{
#name: data,
#path: /hana/data,
#wwns: 600507681082018bc8000000000057e4,600507681082018bc8000000000057e8
#},
#{
#name: log,
#path: /hana/log,
#wwns: 600507681082018bc8000000000057d9,600507681082018bc8000000000057ed7
#},
#{
#name: shared,
#path: /hana/shared,
#wwns: 600507681082018bc8000000000057f1
#}
#]

# For SAP Netweaver swap disk requirement
#swap_disk_wwn: "60050768108002DC6800000000029801"

# ----------------------------- Optional parameters ------------------------------  #
#Uncomment # if you want to use any of there Optional parameters
#host_ip: "1.1.1.1"
#stripe_size: 64K
# only for RHEL installations
#rhel_subscription : {
#username: "",
#password: "",
#release: ""
#}


# for Full Linux Subscription
#full_linux_subscription: true

# to set proxy on client VM  and also for Full Linux Subscription
# private_proxy_ip_port: 172.23.0.12:3128
server_config: {
squid: { enable: false },
ntp: { enable: false },
nfs: { enable: false, nfs_directory: "/NFS;/hana/software" },
dns: { enable: false, dns_servers: "161.26.0.7; 161.26.0.8; 9.9.9.9;" },
awscli: { enable: false }
}
# ----------------------------- Mandatory parameters -----------------------------  #
# Defining all mandatory variables, required to run complete automation suite. Please refer to README if inidividual modules are to be executed and for explianation for variables.

sap_solution: HANA
# As a dictionary
disks_configuration: {
counts: [2,2,1],
names: [data,log,shared],
paths: [/hana/data,/hana/log,/hana/shared],
wwns: [600507681082018bc8000000000057e4,600507681082018bc8000000000057e8,600507681082018bc8000000000057e5,600507681082018bc8000000000057e6,600507681082018bc8000000000057e7]
}

# As a list. Only one type should be present in variable file. Uncomment # if you want to use disks_configuration as a list.
#disks_configuration: [
#{
#name: data,
#path: /hana/data,
#wwns: 600507681082018bc8000000000057e4,600507681082018bc8000000000057e8
#},
#{
#name: log,
#path: /hana/log,
#wwns: 600507681082018bc8000000000057d9,600507681082018bc8000000000057ed7
#},
#{
#name: shared,
#path: /hana/shared,
#wwns: 600507681082018bc8000000000057f1
#}
#]

# For SAP Netweaver swap disk requirement
#swap_disk_wwn: "60050768108002DC6800000000029801"

# ----------------------------- Optional parameters ------------------------------  #
#Uncomment # if you want to use any of there Optional parameters
#host_ip: "1.1.1.1"
#stripe_size: 64K

# only for SuSE installations
#suse_subscription : {
#username: "",
#key: "",
#release: ""
#}


# for Full Linux Subscription
#full_linux_subscription: true

# to set proxy on client VM  and also for Full Linux Subscription
# private_proxy_ip_port: 172.23.0.12:3128
