---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule ansible-core
      - name: Test with molecule
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          ls -l ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add ~/.ssh/private.key
          ssh -i ~/.ssh/private.key -o  ProxyCommand="ssh -W %h:%p root@159.23.91.234" root@10.51.0.12 ls
          cd ./sahityajain123/test_ansible_molecule/
          molecule --debug test
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SAH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          
